n = int(input('Digite um número: '))
print('='*10)
print('A tabuada de {} é:\n'.format(n))
print('{}X1 = {}'.format(n, n*1))
print('{}X2 = {}'.format(n, n*2))
print('{}X3 = {}'.format(n, n*3))
print('{}X4 = {}'.format(n, n*4))
print('{}X5 = {}'.format(n, n*5))
print('{}X6 = {}'.format(n, n*6))
print('{}X7 = {}'.format(n, n*7))
print('{}X8 = {}'.format(n, n*8))
print('{}X9 = {}'.format(n, n*9))
print('{}X10 = {}'.format(n, n*10))
print('='*10)
